### ISSUE TITLE
global name 'UniqueValues' is not defined

### ISSUE THREAD

**Issue by rishikanths** [holderlb/Subdue#1]
Hi Dr. Holder,

When executing the script, I face the following error

```
Traceback (most recent call last):
  File "Subdue.py", line 156, in <module>
    main()
  File "Subdue.py", line 153, in main
    Subdue(parameters, graph)
  File "Subdue.py", line 107, in Subdue
    patternList = DiscoverPatterns(parameters, graph)
  File "Subdue.py", line 54, in DiscoverPatterns
    Pattern.PatternListInsert(extendedPattern, childPatternList, parameters.beamWidth, parameters.valueBased)
  File "/home/rishi/Downloads/PythonSubdue/Pattern.py", line 220, in PatternListInsert
    uniqueValues = UniqueValues(patternList)
NameError: global name 'UniqueValues' is not defined
```
I could not find the function "UniqueValues". Let me know the possible fix.

**Comment by ghost** [comment]
Thanks for the bug report. The fix has been pushed.

Larry Holder

**Comment by rishikanths** [comment]
Thanks for the quick reply and fix.
